import './globals.css';
import { Toaster } from 'react-hot-toast';
import { toastOptions } from '@/config/toastOptions';
import Providers from '@/Providers';

export const metadata = {
    title: 'discord',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <>
                    <Toaster
                        position="top-center"
                        toastOptions={toastOptions}
                    />
                    <Providers>{children}</Providers>
                </>
            </body>
        </html>
    );
}
